cfg_model: !!python/object/new:RNAformer.utils.configuration.SimpleNestedNamespace
  dictitems:
    H_cycles: 1
    L_cycles: 1
    act_enabled: false
    binary_output: true
    cgar_enabled: false
    cycling: 6
    dual_state: false
    enable_brier_halting: false
    enable_monotonicity: false
    enable_smoothness: false
    ff_factor: 4
    ff_kernel: 3
    flash_attn: true
    initializer_range: 0.02
    input_reinjection: false
    key_dim: 16
    learn_ln: true
    ln_eps: 1.0e-05
    max_len: 200
    model_dim: 32
    n_layers: 1
    num_head: 2
    pdb_flag: true
    pos_embedding: true
    precision: '16'
    rel_pos_enc: true
    resi_dropout: 0.1
    rotary_emb: true
    rotary_emb_fraction: 0.5
    seq_vocab_size: 5
    softmax_scale: null
    supervision_decay: 0.7
    trg_vocab_size: 2
    use_bias: true
    use_glu: false
    zero_init: true
  state:
    H_cycles: 1
    L_cycles: 1
    act_enabled: false
    binary_output: true
    cgar_enabled: false
    cycling: 6
    dual_state: false
    enable_brier_halting: false
    enable_monotonicity: false
    enable_smoothness: false
    ff_factor: 4
    ff_kernel: 3
    flash_attn: true
    initializer_range: 0.02
    input_reinjection: false
    key_dim: 16
    learn_ln: true
    ln_eps: 1.0e-05
    max_len: 200
    model_dim: 32
    n_layers: 1
    num_head: 2
    pdb_flag: true
    pos_embedding: true
    precision: '16'
    rel_pos_enc: true
    resi_dropout: 0.1
    rotary_emb: true
    rotary_emb_fraction: 0.5
    seq_vocab_size: 5
    softmax_scale: null
    supervision_decay: 0.7
    trg_vocab_size: 2
    use_bias: true
    use_glu: false
    zero_init: true
cfg_train: !!python/object/new:RNAformer.utils.configuration.SimpleNestedNamespace
  dictitems:
    optimizer:
      _target_: torch.optim.AdamW
      betas: &id001
      - 0.9
      - 0.999
      eps: 1.0e-08
      lr: 0.001
      scheduler_mult_factor: null
      weight_decay: 0.01
    optimizer_param_grouping:
      bias_regularization: false
      normalization_regularization: false
    scheduler:
      decay_factor: 0.1
      num_training_steps: 5000
      num_warmup_steps: 500
      schedule: cosine
    seed: 42
  state:
    optimizer: !!python/object/new:RNAformer.utils.configuration.SimpleNestedNamespace
      dictitems:
        _target_: torch.optim.AdamW
        betas: *id001
        eps: 1.0e-08
        lr: 0.001
        scheduler_mult_factor: null
        weight_decay: 0.01
      state:
        _target_: torch.optim.AdamW
        betas: *id001
        eps: 1.0e-08
        lr: 0.001
        scheduler_mult_factor: null
        weight_decay: 0.01
    optimizer_param_grouping: !!python/object/new:RNAformer.utils.configuration.SimpleNestedNamespace
      dictitems:
        bias_regularization: false
        normalization_regularization: false
      state:
        bias_regularization: false
        normalization_regularization: false
    scheduler: !!python/object/new:RNAformer.utils.configuration.SimpleNestedNamespace
      dictitems:
        decay_factor: 0.1
        num_training_steps: 5000
        num_warmup_steps: 500
        schedule: cosine
      state:
        decay_factor: 0.1
        num_training_steps: 5000
        num_warmup_steps: 500
        schedule: cosine
    seed: 42
data_module: !!python/object:RNAformer.pl_module.datamodule_rna.DataModuleRNA
  _log_hyperparams: false
  allow_zero_length_dataloader_with_multiple_devices: false
  batch_by_token_size: false
  batch_size: 2
  batch_token_size: null
  cache_dir: !!python/object/apply:pathlib.PosixPath
  - /
  - mnt
  - Data
  - GitHub
  - SeniorProject
  - cache
  - baseline
  collator: !!python/object:RNAformer.utils.data.rna.CollatorRNA
    ignore_index: -100
    pad_index: 0
  dataframe_path: /mnt/Data/GitHub/SeniorProject/RNAformer/data/bprna_data.plk
  ignore_index: -100
  logger: &id004 !!python/object/apply:logging.getLogger
  - train_baseline
  max_len: 200
  min_len: 16
  num_cpu_worker: 8
  oversample_pdb: 1
  pad_index: 0
  prepare_data_per_node: true
  random_crop_mat: false
  random_ignore_mat: false
  rng: !!python/object/apply:numpy.random._pickle.__randomstate_ctor
    args:
    - !!python/object/apply:numpy.random._pickle.__bit_generator_ctor
      args:
      - !!python/name:numpy.random._mt19937.MT19937 ''
      state: !!python/tuple
      - bit_generator: MT19937
        state:
          key: !!python/object/apply:numpy._core.multiarray._reconstruct
            args:
            - &id002 !!python/name:numpy.ndarray ''
            - !!python/tuple
              - 0
            - !!binary |
              Yg==
            state: !!python/tuple
            - 1
            - !!python/tuple
              - 624
            - &id003 !!python/object/apply:numpy.dtype
              args:
              - u4
              - false
              - true
              state: !!python/tuple
              - 3
              - <
              - null
              - null
              - null
              - -1
              - -1
              - 0
            - false
            - !!binary |
              KgAAAJOKPLk3RAFxUc966F6tpLRRoULzYIfcorHbIlF43CHskM+2M9rzI6lDzJXDTNUn6jhvB9xV
              dRK4Ytp0aR8kruAdO8uiTeqqrj64+xyK3ppW7C//xWHQ3dHBqLWLB/BQN9xxk6ewui3KunPZ2xmp
              x1GVjuvcTIdXZoCWC2cFaqRktfe1RyYORmKGdEcaAq82U1SnUCVK+Knl9AXtJ2ztXrKPioUSlTG/
              41nWEc+uuzUS0yllegjiCCpXda/kVD5PxIQnAUSrxD2j4Ac8IpT7BVn+/hEQbIiBGdOeEK2tgUOw
              RNHRCg70oPZcPnaYUumYyjJmZ1BdneFdi1G95OjyCirJ/af29DqeX+xfrV/FrTcj/vtYjbJG2Za3
              E135TBowqw8fMOgGrO1EDp4FC9LZLpVdP7yiydfHwQE92YR/rXCaole3tXIymrSD1uNmnjM9O6vr
              FjHNfdY3OFeNvTp0B0egbsEUekXkOn2zk8MSP8ZE3A1991nQ2wV81KcwTDFRIl0ffmaumw6aP3fG
              ato5z8AC9KUYMFccDVcWJ/mMw6pDCpzg6fdgXYkUXm0tUNIKdmJTCUl94QLaJWVB4G4++EQ8CWOY
              6NO2h8XV7+WSTXBxdEbX/Wl85Xt/vfX3ZB6/1BwefX/rZkVQzdTaV/ggy6YfzZ/hiuiT9IwPi83r
              qhlE06j9/pLqGrdTmxXPFBfUQs5Ymlsx0RR/dzh5P3v2S6lG/y07KC2sebjCN63uXUv5DuR6PRR4
              6SlzFOsy75zV9601tfI4TPqadR0hpYdPFuGpA/eaDfYXkoIbi4QYWhl9du3m7sNMYrDAkSK3JlTy
              lNF2nu94Q9ku99YaORP/YfnxMZmOgcDQH4j85/N7Bnrs/cXiZhL5T63300a8Ub0SVzmB5E7C89WR
              a+sasxkSec3vDipSlEIXvd2L6SbhcwhlEZh4DWcYbC5WwIVIB3IUJ3i8R25zHXkZFiqwL2ZhoIUt
              8SBmFrNDFGluJmfENxcoEeVcdA7wq6J7IaDRGG1e8Gh/Yb2U/4wYJwpzkV3O09XbuZICLYdWAohq
              teifbGRzH2kR5dZ04mCeKMBPhx7mfKvBycoWUNQlfV85BCGSJ7egY8Yy8u71bLJRjKZEa+NIDkAE
              gZKxR/0MqEZS+UIqWrEkS6V5Ri7y/RhPtXdUjh/QApwh7my+k/tF37wd3Vf2t0vR6eYyAkMGtWx1
              pyv1Z2MPoHGQhA9AHOcHYFm0l6vQ29s0+gkQRvJDiGPL2sSQOuM+PtCw/+Qur0YIFrzkSQSFh2jr
              KMqC4NUFNFRC4v5IvCUpXtGd86hf2YcKuZpCUOVex7nlbrrCts4Shu2p4nbjyfcnW5Nh/Uz04DZP
              iMDqnZ1uuREfc5t2xScrv53/zdOgXoK8X0G2ezxyO78SBlAGWYxkYb/Hro1yVxeOzYFWTLX1l5uz
              6HOWKp6l1Gb6j7zoqrPZlJ7onBDZy6z09f0zdxPn6MSgcHCVyHfpR7NCuYH1v+AYxUdHOYhVDKB0
              QdIJcF40JDU1+OBtpMEBeDq01TAEJlkHtySgVfLizUQEllMMulReYu6BrH9zKyESiLB7m5yBDJWB
              sp6y24m5i8qE57sWbN4J3WsyKWHUqGsRK+Mh5xcjSvGE7LYTgBvlhRfSW0rsFP0ES7NNMUcFxPPZ
              jDMZCdowGPmSwOO7CNWdAB1cyroIsSe63v90tXhrajXuUXlXfmebu+91Bm8w7D57qD+8zh7OoskE
              CjJAOV9ooFZ6t3vkThk2U5DzzIVXx14V1aJIgcjU0UYz9D0HTvqPtrYqhtpYSvMwzyEOgWP1s1k1
              /x1lVY3E48dei+4Ib0tEplsYSjFCUMEnZv0FLZuQwu1WZUwBTQK5clyVTGUStLBE4TeamvKI9dF5
              Ab+m7GmD77GzEowGsnCz/GDWqJ8zbiUldnM7BGvKFQBePYk3KpNmvI4gKZvtXt1oFsLCqBx/dR/B
              G3ZJQB5j3OVNbab2yVRZsD67XkiZosTJtvj8G4pqS3Fica1NfbuHTsv6kZ/WlH2hF/U1JjHqzvpQ
              hv0fvj9TBQyBeHPNqabaMJE5CMSXzdNb5s3PNbkzxRnheX0BPkdDC73EeFSPqp1fltUcsK5hccuo
              nrimVUvv7CMojZYnWhoI7LAHu7nOTMarEXrpDUtD5/H/FDdqzjfpHN9DgqXLDMEZsrCPdjuDJQXk
              WqSVXPTGgrW41mekNHvdhCZaNbbXyQhxggwqOfHUhezAuD7CapZ0lnvPrQz3CW3Kbn+Xkr4HX6rc
              D91ZgfcIyqpNE2B9kBGP2LkuG/kfJFi8qZA0ezkHN3EI6zh/VUcytF9s1WSWals9F7vV1m55XTd+
              iTWxBmI/v+QJlyxRIFBoBB1O+b9o6qRRNRJM3fR2HXtJtVCY4pE/Q+ZeOIsq24ypfMg9O715fPZE
              IFUjJWm3XmPSBV3IQCaHKQxZisG4K6coZrlhUnJGl1IvWIf7LVfJo12OYJROBOIumnKbefwr5rAM
              S0xU+JKen3rIDVNg7RaEhBvDN++AT9r4KtDD5En+uJw/KR9rlpTr6AD1cs4OhcrDjQX/o65Mds6Z
              I9TGZPVvaUMwNFTL/I7WQOeJjQm6XyayVaYfjiCLXZiwbjlauSdrG/hgwYx0gN/lpCrsCSxvc8Eq
              r4jMevPLF7YCDAggz+E2XGhXiN+FgUh5B96lLUL1yd8mpMwR+98eHKEudKewWmNwDIFe+LyvZiZS
              p6LbLOWMQyNcJVCGGg4wj31pKLghmN++1sKW4xHdkaiIZWCgfOsk2ybiEDwKkbnymgsT1Wt25x5G
              /Z1wE+7Q22F+RMu8UFamCYt1LqGtBtX/NPy1507H8wsmFi9v52Uc5LcX5T0vF4/2XCe7YELyYWIb
              wQbIQYUZB/4+jhnn7eJjGT8iMQEwvULG+eDJAmtFDSMtG0fL61HFqrmYq+EVPaCNEx9KguEYXQO4
              R3iR6axPsVapjyoxidBABhZA5NaOO2K9cBTN3vtGO0nqbVF/WtHtwaB1wY25KgW3jwBzD6kDdLL0
              OsZ7Nh1BgJ93Skxsy4gsX/ATTFdU2UZfyT2VTilqae/UXo19TGlZpApMw3mc5QtGN57dgzDKjE+d
              ABfun8656tYBJIHvLvu0zVqxFy6KKzp0JGJveAFu0tdqjtL1myelxbnY0nFDVsdOoD6/UeyRaeYN
              OfSwCjXg9wWMpgJ5ISok0gSwWUFnzd70Kw3za3QSPaRYDXBziO2/GcNoV9jxmevYgu/rvQtTtimq
              9c5TZ3wR2kb/ga0lME1/PlNl59vUqONhBbO7C5xByOml3N88T5+Z3DEqtZcB
          pos: 624
      - null
    state:
      bit_generator: MT19937
      gauss: 0.0
      has_gauss: 0
      state:
        key: !!python/object/apply:numpy._core.multiarray._reconstruct
          args:
          - *id002
          - !!python/tuple
            - 0
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple
            - 624
          - *id003
          - false
          - !!binary |
            KgAAAJOKPLk3RAFxUc966F6tpLRRoULzYIfcorHbIlF43CHskM+2M9rzI6lDzJXDTNUn6jhvB9xV
            dRK4Ytp0aR8kruAdO8uiTeqqrj64+xyK3ppW7C//xWHQ3dHBqLWLB/BQN9xxk6ewui3KunPZ2xmp
            x1GVjuvcTIdXZoCWC2cFaqRktfe1RyYORmKGdEcaAq82U1SnUCVK+Knl9AXtJ2ztXrKPioUSlTG/
            41nWEc+uuzUS0yllegjiCCpXda/kVD5PxIQnAUSrxD2j4Ac8IpT7BVn+/hEQbIiBGdOeEK2tgUOw
            RNHRCg70oPZcPnaYUumYyjJmZ1BdneFdi1G95OjyCirJ/af29DqeX+xfrV/FrTcj/vtYjbJG2Za3
            E135TBowqw8fMOgGrO1EDp4FC9LZLpVdP7yiydfHwQE92YR/rXCaole3tXIymrSD1uNmnjM9O6vr
            FjHNfdY3OFeNvTp0B0egbsEUekXkOn2zk8MSP8ZE3A1991nQ2wV81KcwTDFRIl0ffmaumw6aP3fG
            ato5z8AC9KUYMFccDVcWJ/mMw6pDCpzg6fdgXYkUXm0tUNIKdmJTCUl94QLaJWVB4G4++EQ8CWOY
            6NO2h8XV7+WSTXBxdEbX/Wl85Xt/vfX3ZB6/1BwefX/rZkVQzdTaV/ggy6YfzZ/hiuiT9IwPi83r
            qhlE06j9/pLqGrdTmxXPFBfUQs5Ymlsx0RR/dzh5P3v2S6lG/y07KC2sebjCN63uXUv5DuR6PRR4
            6SlzFOsy75zV9601tfI4TPqadR0hpYdPFuGpA/eaDfYXkoIbi4QYWhl9du3m7sNMYrDAkSK3JlTy
            lNF2nu94Q9ku99YaORP/YfnxMZmOgcDQH4j85/N7Bnrs/cXiZhL5T63300a8Ub0SVzmB5E7C89WR
            a+sasxkSec3vDipSlEIXvd2L6SbhcwhlEZh4DWcYbC5WwIVIB3IUJ3i8R25zHXkZFiqwL2ZhoIUt
            8SBmFrNDFGluJmfENxcoEeVcdA7wq6J7IaDRGG1e8Gh/Yb2U/4wYJwpzkV3O09XbuZICLYdWAohq
            teifbGRzH2kR5dZ04mCeKMBPhx7mfKvBycoWUNQlfV85BCGSJ7egY8Yy8u71bLJRjKZEa+NIDkAE
            gZKxR/0MqEZS+UIqWrEkS6V5Ri7y/RhPtXdUjh/QApwh7my+k/tF37wd3Vf2t0vR6eYyAkMGtWx1
            pyv1Z2MPoHGQhA9AHOcHYFm0l6vQ29s0+gkQRvJDiGPL2sSQOuM+PtCw/+Qur0YIFrzkSQSFh2jr
            KMqC4NUFNFRC4v5IvCUpXtGd86hf2YcKuZpCUOVex7nlbrrCts4Shu2p4nbjyfcnW5Nh/Uz04DZP
            iMDqnZ1uuREfc5t2xScrv53/zdOgXoK8X0G2ezxyO78SBlAGWYxkYb/Hro1yVxeOzYFWTLX1l5uz
            6HOWKp6l1Gb6j7zoqrPZlJ7onBDZy6z09f0zdxPn6MSgcHCVyHfpR7NCuYH1v+AYxUdHOYhVDKB0
            QdIJcF40JDU1+OBtpMEBeDq01TAEJlkHtySgVfLizUQEllMMulReYu6BrH9zKyESiLB7m5yBDJWB
            sp6y24m5i8qE57sWbN4J3WsyKWHUqGsRK+Mh5xcjSvGE7LYTgBvlhRfSW0rsFP0ES7NNMUcFxPPZ
            jDMZCdowGPmSwOO7CNWdAB1cyroIsSe63v90tXhrajXuUXlXfmebu+91Bm8w7D57qD+8zh7OoskE
            CjJAOV9ooFZ6t3vkThk2U5DzzIVXx14V1aJIgcjU0UYz9D0HTvqPtrYqhtpYSvMwzyEOgWP1s1k1
            /x1lVY3E48dei+4Ib0tEplsYSjFCUMEnZv0FLZuQwu1WZUwBTQK5clyVTGUStLBE4TeamvKI9dF5
            Ab+m7GmD77GzEowGsnCz/GDWqJ8zbiUldnM7BGvKFQBePYk3KpNmvI4gKZvtXt1oFsLCqBx/dR/B
            G3ZJQB5j3OVNbab2yVRZsD67XkiZosTJtvj8G4pqS3Fica1NfbuHTsv6kZ/WlH2hF/U1JjHqzvpQ
            hv0fvj9TBQyBeHPNqabaMJE5CMSXzdNb5s3PNbkzxRnheX0BPkdDC73EeFSPqp1fltUcsK5hccuo
            nrimVUvv7CMojZYnWhoI7LAHu7nOTMarEXrpDUtD5/H/FDdqzjfpHN9DgqXLDMEZsrCPdjuDJQXk
            WqSVXPTGgrW41mekNHvdhCZaNbbXyQhxggwqOfHUhezAuD7CapZ0lnvPrQz3CW3Kbn+Xkr4HX6rc
            D91ZgfcIyqpNE2B9kBGP2LkuG/kfJFi8qZA0ezkHN3EI6zh/VUcytF9s1WSWals9F7vV1m55XTd+
            iTWxBmI/v+QJlyxRIFBoBB1O+b9o6qRRNRJM3fR2HXtJtVCY4pE/Q+ZeOIsq24ypfMg9O715fPZE
            IFUjJWm3XmPSBV3IQCaHKQxZisG4K6coZrlhUnJGl1IvWIf7LVfJo12OYJROBOIumnKbefwr5rAM
            S0xU+JKen3rIDVNg7RaEhBvDN++AT9r4KtDD5En+uJw/KR9rlpTr6AD1cs4OhcrDjQX/o65Mds6Z
            I9TGZPVvaUMwNFTL/I7WQOeJjQm6XyayVaYfjiCLXZiwbjlauSdrG/hgwYx0gN/lpCrsCSxvc8Eq
            r4jMevPLF7YCDAggz+E2XGhXiN+FgUh5B96lLUL1yd8mpMwR+98eHKEudKewWmNwDIFe+LyvZiZS
            p6LbLOWMQyNcJVCGGg4wj31pKLghmN++1sKW4xHdkaiIZWCgfOsk2ybiEDwKkbnymgsT1Wt25x5G
            /Z1wE+7Q22F+RMu8UFamCYt1LqGtBtX/NPy1507H8wsmFi9v52Uc5LcX5T0vF4/2XCe7YELyYWIb
            wQbIQYUZB/4+jhnn7eJjGT8iMQEwvULG+eDJAmtFDSMtG0fL61HFqrmYq+EVPaCNEx9KguEYXQO4
            R3iR6axPsVapjyoxidBABhZA5NaOO2K9cBTN3vtGO0nqbVF/WtHtwaB1wY25KgW3jwBzD6kDdLL0
            OsZ7Nh1BgJ93Skxsy4gsX/ATTFdU2UZfyT2VTilqae/UXo19TGlZpApMw3mc5QtGN57dgzDKjE+d
            ABfun8656tYBJIHvLvu0zVqxFy6KKzp0JGJveAFu0tdqjtL1myelxbnY0nFDVsdOoD6/UeyRaeYN
            OfSwCjXg9wWMpgJ5ISok0gSwWUFnzd70Kw3za3QSPaRYDXBziO2/GcNoV9jxmevYgu/rvQtTtimq
            9c5TZ3wR2kb/ga0lME1/PlNl59vUqONhBbO7C5xByOml3N88T5+Z3DEqtZcB
        pos: 624
  samples_cache_file: bprna_data_len16200_oversampling1_seed42_v7.pth
  seed: 42
  seq_itos:
    0: A
    1: C
    2: G
    3: U
    4: N
  seq_stoi:
    A: 0
    B: 3
    C: 1
    D: 0
    G: 2
    H: 1
    K: 3
    M: 1
    N: 4
    P: 3
    R: 0
    S: 1
    T: 3
    U: 3
    V: 1
    W: 3
    Y: 1
  seq_vocab:
  - A
  - C
  - G
  - U
  - N
  seq_vocab_size: 5
  shuffle_pool_size: 1000
  test_sets: []
  train_seed: 0
  trainer: null
  valid_sets:
  - bprna_ts0
py_logger: *id004
